name: Telegram Bot Scheduler

on:
  schedule:
    # Führe den Bot zu den angegebenen Zeiten aus
    - cron: "0 08 * * *"
    - cron: "0 12 * * *"
    - cron: "0 16 * * *"
    - cron: "0 20 * * *"
  workflow_dispatch:

jobs:
  telegram-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Repository klonen
        uses: actions/checkout@v3

      - name: Python installieren
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"

      - name: Abhängigkeiten installieren
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Bot ausführen
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: python bot.py

      - name: Kapitelnummer aktualisieren und committen
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add current_chapter.txt
          git commit -m "Update current_chapter.txt" || echo "Nichts zu committen"
          git push
