name: Twitter Bot Scheduler

on:
  schedule:
    # Führe den Bot um 11:00 und 18:00 Uhr UTC aus
    - cron: "0 00 * * *"
    - cron: "0 02 * * *"
    - cron: "0 04 * * *"
    - cron: "0 06 * * *"
    - cron: "0 09 * * *"
    - cron: "0 11 * * *"
    - cron: "0 13 * * *"
    - cron: "0 15 * * *"
    - cron: "0 17 * * *"
    - cron: "0 19 * * *"
    - cron: "0 21 * * *"
    - cron: "0 23 * * *"
  workflow_dispatch:
jobs:
  tweet:
    runs-on: ubuntu-latest

    steps:
    - name: Repository klonen
      uses: actions/checkout@v3

    - name: Python installieren
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"

    - name: Abhängigkeiten installieren
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Bot ausführen
      env:
        BEARER_TOKEN: ${{ secrets.BEARER_TOKEN }}
        API_KEY: ${{ secrets.API_KEY }}
        API_SECRET: ${{ secrets.API_SECRET }}
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        ACCESS_SECRET: ${{ secrets.ACCESS_SECRET }}
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: python bot.py
