name: Twitter Bot Scheduler

on:
  schedule:
    # Führe den Bot zu den angegebenen Zeiten aus
    - cron: "0 00 * * *"
    - cron: "0 02 * * *"
    - cron: "0 04 * * *"
    - cron: "0 06 * * *"
    - cron: "0 08 * * *"
    - cron: "0 10 * * *"
    - cron: "0 12 * * *"
    - cron: "0 14 * * *"
    - cron: "0 16 * * *"
    - cron: "0 18 * * *"
    - cron: "0 20 * * *"
    - cron: "0 22 * * *"
  workflow_dispatch:

jobs:
  tweet:
    runs-on: ubuntu-latest

    steps:
    - name: Repository klonen
      uses: actions/checkout@v3

    - name: Python installieren
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"

    - name: Abhängigkeiten installieren
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Bot ausführen
      env:
        BEARER_TOKEN: ${{ secrets.BEARER_TOKEN }}
        API_KEY: ${{ secrets.API_KEY }}
        API_SECRET: ${{ secrets.API_SECRET }}
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        ACCESS_SECRET: ${{ secrets.ACCESS_SECRET }}
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: python bot.py

    - name: Kapitelnummer aktualisieren und committen
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add current_chapter.txt
        git commit -m "Update current_chapter.txt" || echo "Nichts zu committen"
        git push
